site_name: Data Science course
docs_dir: docs
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - navigation.tracking
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - header.autohide
  icon:
    repo: fontawesome/brands/github
  custom_dir: theme
markdown_extensions:
  - admonition
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
repo_url: https://github.com/ML-boot-camp/sessions
edit_uri: edit/master/
plugins:
  - search
  - tooltips
  - mkdocs-jupyter:
      include_source: True
  - charts:
      use_data_path: false
extra_css:
  - css/hint.min.css
  - css/style.css
extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
