name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-tooltips 'mkdocs-charts-plugin=0.0.8' mkdocs-jupyter
      - run: mkdocs gh-deploy --force
